### ISSUE TITLE
Link to YouTube video points to wrong timestamp

### ISSUE THREAD

**Issue by sgwilym** [joshwnj/6-ways-to-win#1]
The 'watch' link (https://youtu.be/skzcEKewOwc?t=2h7m57s) links to a point halfway into José Perez’ talk on progressive image rendering.

Would love to see this talk, and not sure where to find it!

**Comment by joshwnj** [comment]
@sgwilym Ah you're right - sorry, try this one instead :) https://youtu.be/skzcEKewOwc?t=3h12m29s
